name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation:
  args: ^1.5.0
  shelf: ^0.7.5
  meta: ^1.1.8
  json_annotation: ^3.0.1
  hive: ^1.4.1+1

dev_dependencies:
  build_runner:
  freezed:
  pedantic: ^1.8.0
  extra_pedantic: ^1.2.0
  json_serializable: ^3.2.0
  hive_generator: 0.7.0+2
